# SPDX-FileCopyrightText: 2023-2025 Enedis
# SPDX-License-Identifier: MIT

include:
  - project: 'dev/commun/templates'
    ref: 'v2'
    file: 'templates/java-maven-test.yml'
  - project: 'dev/commun/templates'
    ref: 'v2'
    file: 'templates/java-maven-publish.yml'

default:
  tags:
    - hadock
variables:
  MAVEN_IMAGE: ${PLACIDE_RELEASES_DOCKER_REPO}.${REPOSITOI_ZONE_HOSTNAME}/maven:3.8.8-jdk17-alpine-enedis-3
  KYSS_EXPORT: "true"

stages:
  - test
  - deploy

maven-test:
  only:
    - branches
  stage: test
  extends: .test-maven
  variables:
    MAVEN_CLI: "mvn"
    MAVEN_ARGS: "-U -B -s ./.mvn/settings.xml"
    MAVEN_GOALS: "verify"

maven-publish:
  only:
    - tags
  stage: deploy
  extends: .publish-maven
  variables:
    MAVEN_CLI: "mvn"
    MAVEN_ARGS: "-s ./.mvn/settings.xml"
