package fr.enedis.grafana.dsl.dashboard

import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import fr.enedis.grafana.dsl.dashboard
import fr.enedis.grafana.dsl.json.set
import fr.enedis.grafana.dsl.jsonFile
import fr.enedis.grafana.dsl.panels.panel
import fr.enedis.grafana.dsl.shouldEqualToJson
import fr.enedis.grafana.dsl.time.h
import fr.enedis.grafana.dsl.time.m
import fr.enedis.grafana.dsl.time.now
import fr.enedis.grafana.dsl.time.off
import java.lang.IllegalArgumentException

class DashboardBuilderTest {

    @Test
    fun `should correct create minimal example`() {
        // expect
        val minimalDashboard = dashboard("TestAutogenerated") {}

        // that
        minimalDashboard shouldEqualToJson jsonFile("MinimalDashboard.json")
    }

    @Test
    fun `should correct change time range`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            timeRange = now - 3.h..now
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithTimeRange.json")
    }

    @Test
    fun `should set uid`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            uid = "component"
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithUid.json")
    }

    @Test
    fun `should set false to refresh property when refresh is off`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            refresh = off
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithOffRefresh.json")
    }

    @Test
    fun `should contains 2 tags when 1 tag added`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            tags += "test"
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithTags.json")
    }

    @Test
    fun `should add panel to board when panels is called`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            panels {
                panel(title = "Test Panel") {
                    properties {
                        it["type"] = "graph"
                    }
                }
            }
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithEmptyPanel.json")
    }

    @Test
    fun `should add variable when variable is created`() {
        // expect
        val dashboard = dashboard("TestAutogenerated") {
            @Suppress("UNUSED_VARIABLE")
            val variable by variables.interval(1.m, 10.m)
        }

        // that
        dashboard shouldEqualToJson jsonFile("DashboardWithVariable.json")
    }

    @Test
    fun `should create an editable dashboard`() {
        // expect
        val dashboard = dashboard("Editable dashboard") {
            editable = true
            panels {
                panel(title = "Test Panel") {
                    properties {
                        it["type"] = "graph"
                    }
                }
            }
        }

        // that
        dashboard shouldEqualToJson jsonFile("EditableDashboard.json")
    }

    @Test
    fun `should throw exception if uid length out of bound`() {

        val illegalArgumentException = Assertions.assertThrows(IllegalArgumentException::class.java) {
            dashboard("TestAutogenerated") {
                uid = "bulk-payouts-processor-commoninfo-database"
            }
        }
        Assertions.assertEquals(true, illegalArgumentException.message?.matches(Regex(".*uid must be between 0 and 40.*")));

    }
}