name: Build, Increment Version, Tag, Release, and Snapshot

on:
  push:
    branches: [main]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Increment version and create tag
        run: |
          mvn release:prepare -DreleaseVersion=NEXT_MINOR_VERSION -DtagName=v${project.version} -DdevelopmentVersion=${project.version}-SNAPSHOT -Dusername=${{ github.actor }} -Dpassword=${{ secrets.GITHUB_TOKEN }}
          mvn release:perform

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body: |
            # Release notes (TODO)

      - name: Update SNAPSHOT version + 1
        run: |
          mvn versions:set -DnewVersion=${project.version}-SNAPSHOT
          git commit -am "Updated SNAPSHOT version"
          git push