#SPDX-FileCopyrightText: 2021-2022 NBCO YooMoney LLC
#SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v4